# Netlify configuration for crypto-online-casino.com
[build]
  command = "npm run build"
  # Laat Netlify zelf bepalen wat gepubliceerd wordt (App Router gebruikt server rendering)
  publish = ".next"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"
