export const topBonuses = [
  {
    name: "BitStarz",
    image: "bitstarz.png",
    bonusTitle: "Award Winning Casino",
    description: "Sign up now to an Award Winning Casino",
    details: "Accepting 500+ cryptocurrencies for deposits and withdrawals.",
    slug: "bitstarz",
    bonus: "Get up to 5 BTC bonus!",
    bonusCurrency: "BTC",
    bonusAmount: "5",
    bonusType: "Welcome Bonus",
    url: "https://www.bitstarz.com/"
  },
  {
    name: "Stake",
    image: "stake.png",
    bonusTitle: "Up to 10% rakeback!",
    description: "Lightning fast payouts & sports",
    details: "Crypto sportsbook & casino with instant withdrawals and rakeback.",
    slug: "stake",
    bonus: "Up to 10% rakeback!",
    bonusCurrency: "USDT",
    bonusAmount: "10",
    bonusType: "Rakeback",
    url: "https://stake.com/"
  },
  {
    name: "7Bit",
    image: "7bit.png",
    bonusTitle: "Up to 1.5 BTC + 100 Free Spins!",
    description: "Classic slots & crypto games",
    details: "A classic crypto casino with a wide game selection and fast payouts.",
    slug: "7bit",
    bonus: "Up to 1.5 BTC + 100 Free Spins!",
    bonusCurrency: "BTC",
    bonusAmount: "1.5",
    bonusType: "Welcome Bonus",
    url: "https://7bitcasino.com/"
  },
  {
    name: "Betplay",
    image: "betplay.png",
    bonusTitle: "Top crypto games & sports",
    description: "Crypto-friendly and mobile-first",
    details: "Enjoy crypto betting on sports and casino games in a sleek interface.",
    slug: "betplay",
    bonus: "Up to 1 BTC Sports Welcome Bonus",
    bonusCurrency: "BTC",
    bonusAmount: "1",
    bonusType: "Sports Bonus",
    url: "https://www.betplay.io/"
  },
  {
    name: "Cryptoloko",
    image: "cryptoloko.png",
    bonusTitle: "Unlock LOKO rewards!",
    description: "Colorful & fast crypto casino",
    details: "Play unique games and win big with the LOKO crypto token.",
    slug: "crypto-loko",
    bonus: "Get LOKO Token Cashback",
    bonusCurrency: "LOKO",
    bonusAmount: "Variable",
    bonusType: "Cashback",
    url: "https://cryptoloko.com/"
  },
  {
    name: "DreamCasino",
    image: "dreamcasino.png",
    bonusTitle: "Live dealers & massive jackpots",
    description: "Immersive Vegas-style experience",
    details: "Streamed live casino games and massive jackpots await you.",
    slug: "dreamcasino",
    bonus: "Claim a Live Dealer Bonus Package",
    bonusCurrency: "BTC",
    bonusAmount: "3",
    bonusType: "Live Casino Bonus",
    url: "https://dreamcasino.io/"
  },
  {
    name: "PrismCasino",
    image: "prismcasino.png",
    bonusTitle: "Exclusive crypto deals",
    description: "Bright, bold, and fast",
    details: "Enjoy a colorful interface with generous bonuses.",
    slug: "prismcasino",
    bonus: "300% Crypto Welcome Bonus!",
    bonusCurrency: "USDT",
    bonusAmount: "300",
    bonusType: "Welcome Bonus",
    url: "https://www.prismcasino.com/"
  },
  {
    name: "Placeholder",
    image: "placeholder.png",
    bonusTitle: "Coming soon...",
    description: "New casino launching soon",
    details: "We're reviewing this crypto casino right now!",
    slug: "placeholder1",
    bonus: "New bonus coming soon...",
    bonusCurrency: "BTC",
    bonusAmount: "0",
    bonusType: "Unknown",
    url: "https://crypto-online-casino.com/"
  },
  {
    name: "Placeholder",
    image: "placeholder.png",
    bonusTitle: "Coming soon...",
    description: "New crypto brand",
    details: "Stay tuned for updates on this upcoming crypto brand.",
    slug: "placeholder2",
    bonus: "Details will be revealed shortly!",
    bonusCurrency: "BTC",
    bonusAmount: "0",
    bonusType: "Unknown",
    url: "https://crypto-online-casino.com/"
  }
];
