export const topCasinos = [
  {
    name: "BitStarz",
    image: "bitstarz.png",
    bonus: "Get up to 5 BTC Bonus!",
    description: "Award-winning crypto casino",
    details: "Play at the most awarded crypto casino with fast payouts and thousands of games.",
    slug: "bitstarz",
  },
  {
    name: "Wild Vegas",
    image: "wildvegas.png",
    bonus: "100% bonus + Free Spins",
    description: "Get your wild bonus action here!",
    details: "Claim your exclusive Wild Vegas bonus and enjoy top slots and live games.",
    slug: "wildevegas",
  },
  {
    name: "7Bit",
    image: "7bit.png",
    bonus: "Up to 1.5 BTC + 100 Free Spins!",
    description: "Classic slots & crypto games",
    details: "A classic crypto casino with a wide game selection and fast payouts.",
    slug: "7bit",
  },
  {
    name: "Cloudbet",
    image: "cloudbet.png",
    bonus: "100% up to 5 BTC!",
    description: "Crypto sportsbook & high bonuses",
    details: "Bet on sports and play 2000+ casino games with instant crypto payouts.",
    slug: "cloudbet",
  },
  {
    name: "Crypto Loko",
    image: "cryptoloko.png",
    bonus: "Unlock LOKO rewards!",
    description: "Colorful & fast crypto casino",
    details: "Play unique games and win big with the LOKO crypto token.",
    slug: "crypto-loko",
  },
  {
    name: "Dreams",
    image: "dreamscasino.png",
    bonus: "200% Welcome Bonus!",
    description: "Immersive Vegas-style experience",
    details: "Streamed live casino games and massive jackpots await you.",
    slug: "dreams",
  },
  {
    name: "Betzard",
    image: "betzard.png",
    bonus: "100% up to 1 BTC + 100 FS!",
    description: "Top crypto casino",
    details: "Enjoy top-tier slots, live casino, and sports betting with crypto.",
    slug: "betzard",
  },
  {
    name: "PrismCasino",
    image: "prismcasino.png",
    bonus: "Exclusive crypto deals",
    description: "Bright, bold, and fast",
    details: "Enjoy a colorful interface with generous bonuses.",
    slug: "prismcasino",
  },
  {
    name: "Slots of Vegas",
    image: "slotsofvegas.png",
    bonus: "Claim jouw welkomstbonus!",
    description: "Classic Vegas-style crypto casino",
    details: "Spin the reels at Slots of Vegas and grab your exclusive welcome bonus.",
    slug: "slotsofvegas",
  },
  {
    name: "Coinpoker",
    image: "coinpoker.png",
    bonus: "Exclusive poker bonuses!",
    description: "Crypto poker room",
    details: "Play poker with crypto and take advantage of unique promotions.",
    slug: "coinpoker",
  },
];
